import Header from "@/components/Header";
import "./globals.css";
import Footer from "@/components/Footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="px-[8vw] py-4 mx-auto bg-[#FFFFFE] ">
        <Header />
        <main>{children}</main>
      </body>
      <Footer />
    </html>
  );
}
