function Footer() {
  return (
    <div className="bg-gray-700/40 text-white">
      <h1 className="">
        Simple responsive blog site example with modern and minimalist black and
        white design{" "}
      </h1>
      <h3 className="text-sm">
        All photos and articles are generated by LeonardoAi
      </h3>
      <h1 className="text-xs">
        This is a NextJS 13.4 project with TailwindCSS
      </h1>
    </div>
  );
}

export default Footer;
